import { XpraConnectionOptions } from "xpra-html5-client";

export const xpraOptions: Partial<XpraConnectionOptions> = {
	reconnect: true,
	connectionTimeout: 30000,
	reconnectInterval: 5000,
	reconnectAttempts: 3,
	pingInterval: 5000,
	bandWidthLimit: 0,
	shareSession: true,
	username: "",
	display: "",
	password: "",
	showStartMenu: true,
	fileTransfer: true,
	clipboardImages: true,
	clipboardDirection: "both",
	clipboard: true,
	printing: false,
	bell: true,
	audio: true,
	video: false,
	nativeVideo: false,
	cursor: true,
	keyboard: true,
	mouse: true,
	tray: true,
	notifications: true,
	ssl: false,
	encryption: null,
	encryptionKey: "",
	encoder: "auto",
	openUrl: true,
	swapKeys: false,
	keyboardLayout: "us",
	exitWithChildren: false,
	exitWithClient: false,
	startCommand: "",
	reverseScrollX: false,
	reverseScrollY: false,
	debugPackets: ["general", "window", "notification", "clipboard"],
	showStatistics: false,
	stealSession: true,
};
